branch-defaults:
  develop:
    environment: DjangoCircleci-env
  master:
    environment: DjangoCircleci-env
global:
  application_name: django-circleci
  branch: null
  default_ec2_keyname: null
  default_platform: Docker 18.06.1-ce
  default_region: ap-southeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application